### ISSUE TITLE
Discretize change to default

### ISSUE THREAD

**Issue by mohsen-ghaffari1992** [itu-square/symsim#115]
Since we have lots of examples that are in discretized state space, we need to change the discretize definition.

**Comment by wasowski** [comment]
hmm, I do not know what this means.  Does anybody remember?

**Comment by mohsen-ghaffari1992** [comment]
Unfortunately, I cannot remember what was the point about. I just remember that you said we need an issue like this and told me to put it in Git. If I remember something, I will put more description here.
